### ISSUE TITLE
mobile view

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/searchBox#11]
is the website compatible with mobile devices, cause it doesn't look like it does

**Comment by mjmajadly** [comment]
![Screenshot_20201105-140040_Chrome](https://user-images.githubusercontent.com/43019810/98238780-99607b00-1f6f-11eb-8f6f-da03445f3dbe.jpg)

![Capture](https://user-images.githubusercontent.com/43019810/98238787-9c5b6b80-1f6f-11eb-81d2-d1a0ad081c72.PNG)
