### ISSUE TITLE
frontend testing 

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/searchBox#12]
you have a couple of nice looking pure functions that can be tested 😎 .

*testing is lovely isn't it*

**Comment by mjmajadly** [comment]
![50a0c0a31c9be5849a21ceb1bf7f0737d69d5f21da93b7836ff725e2279ba2c9](https://user-images.githubusercontent.com/43019810/98240611-57850400-1f72-11eb-8b89-76194a29d3a7.jpg)
