### ISSUE TITLE
TRy to concatinate this to your website address :  public/img/screenshot.PNG

### ISSUE THREAD

**Issue by muhammadawwad9** [WebAhead7/searchBox#13]
![Screenshot from 2020-11-05 12-39-28](https://user-images.githubusercontent.com/60406664/98230961-78465d00-1f64-11eb-9cf8-a7a8a3344a1c.png)

**Comment by ghost** [comment]
I don't understand the issue, @mjmajadly what the screenshot is used for ?

**Comment by mjmajadly** [comment]
the screenshot is for the readme file not the site
