### ISSUE TITLE
duplicate https.get

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/searchBox#14]
how about instead of having 2 https.get
https://github.com/WebAhead7/SimilarWords/blob/main/server/handlers/dataHandler.js#L4-L18
https://github.com/WebAhead7/SimilarWords/blob/main/server/handlers/inputHandler.js#L4-L17

have a separate file that exports the function that does an api request, that function would take a url and return a promise

**Comment by rakad-kh** [comment]
Hi Mario, I've added api.js file that do that.
Also notice that I've meged the 2 file: dataHandler.js & putHandler.js,  into one dataHandler.js file; adding more parameters to the dataHandler function to determine whereas we ask for "/data" or "/curr".
for further information check router.js file.
Thanks bro.

for
