### ISSUE TITLE
handling errors

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/searchBox#15]
couple of parts of the code errors are not being handled, and if not handled you server will crash and in realty a crashing server is painful 😅 

https://github.com/WebAhead7/SimilarWords/blob/main/server/handlers/dataHandler.js#L25-L27
https://github.com/WebAhead7/SimilarWords/blob/main/server/handlers/inputHandler.js#L25-L27

**Comment by rakad-kh** [comment]
I have added log() to it, thanks Mario

**Comment by Karyum** [comment]
a log is good but it's not enough for the user, if the user is trying to see some data then he would be stuck on an empty page waiting for a response, so also send a response when a message occurs

**Comment by rakad-kh** [comment]
Hi Mario, can you check that?
https://github.com/WebAhead7/SimilarWords/blob/main/server/handlers/dataHandler.js#L12-L19

is it good enough? or should I do something else?

**Comment by Karyum** [comment]
this wouldn't work on nodejs, is your server even able to run ? if it does then try going to the route

**Comment by rakad-kh** [comment]
you are right,
I've fixed it that way; https://github.com/WebAhead7/SimilarWords/blob/main/server/handlers/dataHandler.js#L12-L17
Thanks body
